[package]
name = "libcorefs-tools_tests"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
name = "libcorefs_tools_tests"
path = "src/lib.rs"

[dependencies]
libcorefs-tools = { path = "../libcorefs-tools", features = ["host"] }
corefs-core = { path = "../../../corefs/corefs-core", default-features = false, features = ["std", "crypto"] }
