[package]
name = "libimage"
version = "0.1.0"
edition = "2021"

[lib]
name = "libimage"
path = "src/lib.rs"

[features]
default = []
host = []

[dependencies]
libheap = { path = "../libheap", optional = true }
libsyscall = { path = "../libsyscall", optional = true }

[profile.dev]
panic = "abort"
opt-level = 2

[profile.release]
panic = "abort"

[workspace]
