fn named_color(name: &str) -> Option<u32> {
    match name {
        // Basic colors
        "black" => Some(0xFF000000),
        "white" => Some(0xFFFFFFFF),
        "red" => Some(0xFFFF0000),
        "green" => Some(0xFF008000),
        "lime" => Some(0xFF00FF00),
        "blue" => Some(0xFF0000FF),
        "yellow" => Some(0xFFFFFF00),
        "orange" => Some(0xFFFFA500),
        "purple" => Some(0xFF800080),
        "gray" | "grey" => Some(0xFF808080),
        "silver" => Some(0xFFC0C0C0),
        "cyan" | "aqua" => Some(0xFF00FFFF),
        "magenta" | "fuchsia" => Some(0xFFFF00FF),
        "navy" => Some(0xFF000080),
        "teal" => Some(0xFF008080),
        "maroon" => Some(0xFF800000),
        "olive" => Some(0xFF808000),
        "transparent" => Some(0x00000000),
        // Reds/pinks
        "indianred" => Some(0xFFCD5C5C),
        "lightcoral" => Some(0xFFF08080),
        "salmon" => Some(0xFFFA8072),
        "darksalmon" => Some(0xFFE9967A),
        "lightsalmon" => Some(0xFFFFA07A),
        "crimson" => Some(0xFFDC143C),
        "firebrick" => Some(0xFFB22222),
        "darkred" => Some(0xFF8B0000),
        "pink" => Some(0xFFFFC0CB),
        "lightpink" => Some(0xFFFFB6C1),
        "hotpink" => Some(0xFFFF69B4),
        "deeppink" => Some(0xFFFF1493),
        "mediumvioletred" => Some(0xFFC71585),
        "palevioletred" => Some(0xFFDB7093),
        // Oranges
        "coral" => Some(0xFFFF7F50),
        "tomato" => Some(0xFFFF6347),
        "orangered" => Some(0xFFFF4500),
        "darkorange" => Some(0xFFFF8C00),
        // Yellows
        "gold" => Some(0xFFFFD700),
        "lightyellow" => Some(0xFFFFFFE0),
        "lemonchiffon" => Some(0xFFFFFACD),
        "papayawhip" => Some(0xFFFFEFD5),
        "moccasin" => Some(0xFFFFE4B5),
        "peachpuff" => Some(0xFFFFDAB9),
        "palegoldenrod" => Some(0xFFEEE8AA),
        "khaki" => Some(0xFFF0E68C),
        "darkkhaki" => Some(0xFFBDB76B),
        // Greens
        "lawngreen" => Some(0xFF7CFC00),
        "chartreuse" => Some(0xFF7FFF00),
        "limegreen" => Some(0xFF32CD32),
        "forestgreen" => Some(0xFF228B22),
        "darkgreen" => Some(0xFF006400),
        "greenyellow" => Some(0xFFADFF2F),
        "yellowgreen" => Some(0xFF9ACD32),
        "springgreen" => Some(0xFF00FF7F),
        "mediumspringgreen" => Some(0xFF00FA9A),
        "lightgreen" => Some(0xFF90EE90),
        "palegreen" => Some(0xFF98FB98),
        "darkseagreen" => Some(0xFF8FBC8F),
        "mediumseagreen" => Some(0xFF3CB371),
        "seagreen" => Some(0xFF2E8B57),
        "olivedrab" => Some(0xFF6B8E23),
        "darkolivegreen" => Some(0xFF556B2F),
        // Cyans
        "lightcyan" => Some(0xFFE0FFFF),
        "paleturquoise" => Some(0xFFAFEEEE),
        "aquamarine" => Some(0xFF7FFFD4),
        "turquoise" => Some(0xFF40E0D0),
        "mediumturquoise" => Some(0xFF48D1CC),
        "darkturquoise" => Some(0xFF00CED1),
        "lightseagreen" => Some(0xFF20B2AA),
        "cadetblue" => Some(0xFF5F9EA0),
        "darkcyan" => Some(0xFF008B8B),
        // Blues
        "lightsteelblue" => Some(0xFFB0C4DE),
        "powderblue" => Some(0xFFB0E0E6),
        "lightblue" => Some(0xFFADD8E6),
        "skyblue" => Some(0xFF87CEEB),
        "lightskyblue" => Some(0xFF87CEFA),
        "deepskyblue" => Some(0xFF00BFFF),
        "dodgerblue" => Some(0xFF1E90FF),
        "cornflowerblue" => Some(0xFF6495ED),
        "steelblue" => Some(0xFF4682B4),
        "royalblue" => Some(0xFF4169E1),
        "mediumblue" => Some(0xFF0000CD),
        "darkblue" => Some(0xFF00008B),
        "midnightblue" => Some(0xFF191970),
        // Purples
        "lavender" => Some(0xFFE6E6FA),
        "thistle" => Some(0xFFD8BFD8),
        "plum" => Some(0xFFDDA0DD),
        "violet" => Some(0xFFEE82EE),
        "orchid" => Some(0xFFDA70D6),
        "mediumorchid" => Some(0xFFBA55D3),
        "mediumpurple" => Some(0xFF9370DB),
        "rebeccapurple" => Some(0xFF663399),
        "blueviolet" => Some(0xFF8A2BE2),
        "darkviolet" => Some(0xFF9400D3),
        "darkorchid" => Some(0xFF9932CC),
        "darkmagenta" => Some(0xFF8B008B),
        "indigo" => Some(0xFF4B0082),
        "slateblue" => Some(0xFF6A5ACD),
        "darkslateblue" => Some(0xFF483D8B),
        "mediumslateblue" => Some(0xFF7B68EE),
        // Browns
        "brown" => Some(0xFFA52A2A),
        "cornsilk" => Some(0xFFFFF8DC),
        "blanchedalmond" => Some(0xFFFFEBCD),
        "bisque" => Some(0xFFFFE4C4),
        "navajowhite" => Some(0xFFFFDEAD),
        "wheat" => Some(0xFFF5DEB3),
        "burlywood" => Some(0xFFDEB887),
        "tan" => Some(0xFFD2B48C),
        "rosybrown" => Some(0xFFBC8F8F),
        "sandybrown" => Some(0xFFF4A460),
        "goldenrod" => Some(0xFFDAA520),
        "darkgoldenrod" => Some(0xFFB8860B),
        "peru" => Some(0xFFCD853F),
        "chocolate" => Some(0xFFD2691E),
        "saddlebrown" => Some(0xFF8B4513),
        "sienna" => Some(0xFFA0522D),
        // Whites
        "snow" => Some(0xFFFFFAFA),
        "honeydew" => Some(0xFFF0FFF0),
        "mintcream" => Some(0xFFF5FFFA),
        "azure" => Some(0xFFF0FFFF),
        "aliceblue" => Some(0xFFF0F8FF),
        "ghostwhite" => Some(0xFFF8F8FF),
        "whitesmoke" => Some(0xFFF5F5F5),
        "seashell" => Some(0xFFFFF5EE),
        "beige" => Some(0xFFF5F5DC),
        "oldlace" => Some(0xFFFDF5E6),
        "floralwhite" => Some(0xFFFFFAF0),
        "ivory" => Some(0xFFFFFFF0),
        "antiquewhite" => Some(0xFFFAEBD7),
        "linen" => Some(0xFFFAF0E6),
        "lavenderblush" => Some(0xFFFFF0F5),
        "mistyrose" => Some(0xFFFFE4E1),
        // Grays
        "gainsboro" => Some(0xFFDCDCDC),
        "lightgray" | "lightgrey" => Some(0xFFD3D3D3),
        "darkgray" | "darkgrey" => Some(0xFFA9A9A9),
        "dimgray" | "dimgrey" => Some(0xFF696969),
        "lightslategray" | "lightslategrey" => Some(0xFF778899),
        "slategray" | "slategrey" => Some(0xFF708090),
        "darkslategray" | "darkslategrey" => Some(0xFF2F4F4F),
        _ => Option::None,
    }
}

// ---------------------------------------------------------------------------
// Dimension / number parsing
// ---------------------------------------------------------------------------
