use crate::prelude::*;

const ELF_MAGIC: &[u8; 4] = b"\x7fELF";
const ELFCLASS64: u8 = 2;
const ELFDATA2LSB: u8 = 1;
const ET_EXEC: u16 = 2;
const EM_X86_64: u16 = 0x3e;
const PT_LOAD: u32 = 1;
const PF_X: u32 = 1;
const PF_W: u32 = 2;
const PF_R: u32 = 4;
const ANYOS_USER_BASE: u64 = 0x0800_0000;
const KERNEL_SPACE_BASE: u64 = 0xffff_8000_0000_0000;
const PAGE_SIZE: u64 = 4096;

#[derive(Debug, Clone, Copy)]
pub struct Elf64Header {
    pub entry: u64,
    pub phoff: usize,
    pub phentsize: usize,
    pub phnum: usize,
}

#[derive(Debug, Clone, Copy)]
pub struct ProgramHeader {
    pub ty: u32,
    pub flags: u32,
    pub offset: u64,
    pub vaddr: u64,
    pub paddr: u64,
    pub filesz: u64,
    pub memsz: u64,
    pub align: u64,
}

/// Validate the ELF contract expected by the anyOS user-program loader.
///
/// This is the compiler-native counterpart to the old `anyelf`/bundle
/// conversion path: user binaries should be emitted as loader-ready ELF64
/// executables instead of being post-processed by a host helper.
pub fn validate_user_elf(data: &[u8]) -> Result<(), String> {
    let hdr = parse_elf64_header(data)?;
    let headers = program_headers(data, &hdr)?;
    let mut found_entry_segment = None;

    for ph in headers.iter().filter(|ph| ph.ty == PT_LOAD) {
        if ph.vaddr < ANYOS_USER_BASE {
            return Err(format!(
                "ELF64 segment below 128 MiB identity-map boundary: {:#x}",
                ph.vaddr
            ));
        }
        if ph.vaddr >= KERNEL_SPACE_BASE {
            return Err(format!("ELF64 segment in kernel space: {:#x}", ph.vaddr));
        }
        let end = ph
            .vaddr
            .checked_add(ph.memsz)
            .ok_or_else(|| "ELF64 segment vaddr+memsz overflow".to_string())?;
        if end > KERNEL_SPACE_BASE {
            return Err("ELF64 segment crosses into kernel space".to_string());
        }
        if ph.filesz > ph.memsz {
            return Err("ELF64 segment p_filesz exceeds p_memsz".to_string());
        }
        let file_end = ph
            .offset
            .checked_add(ph.filesz)
            .ok_or_else(|| "ELF64 segment offset+filesz overflow".to_string())?;
        if file_end > data.len() as u64 {
            return Err("ELF64 segment reads past end of file".to_string());
        }
        if ph.align != 0 && !ph.align.is_power_of_two() {
            return Err("ELF64 segment p_align is not a power of two".to_string());
        }
        if ph.align > 1 && ph.offset % ph.align != ph.vaddr % ph.align {
            return Err("ELF64 segment p_offset and p_vaddr alignment mismatch".to_string());
        }
        if contains_addr(ph, hdr.entry) {
            found_entry_segment = Some(*ph);
        }
    }

    let Some(entry_segment) = found_entry_segment else {
        return Err(format!(
            "ELF64 entry point outside PT_LOAD segments: {:#x}",
            hdr.entry
        ));
    };
    if entry_segment.flags & PF_X == 0 {
        return Err("ELF64 entry point is not in an executable segment".to_string());
    }
    if entry_segment.flags & PF_R == 0 {
        return Err("ELF64 entry point is not in a readable segment".to_string());
    }

    Ok(())
}

/// Validate the `_start` ABI stub generated by anyrc for normal bin crates.
pub fn validate_generated_start_stub(data: &[u8]) -> Result<(), String> {
    let hdr = parse_elf64_header(data)?;
    let entry_segment = program_headers(data, &hdr)?
        .into_iter()
        .find(|ph| ph.ty == PT_LOAD && contains_addr(ph, hdr.entry))
        .ok_or_else(|| "ELF64 entry point outside PT_LOAD segments".to_string())?;
    let entry_off = entry_segment
        .offset
        .checked_add(hdr.entry - entry_segment.vaddr)
        .ok_or_else(|| "ELF64 entry file offset overflow".to_string())?
        as usize;
    if entry_off + 20 > data.len() {
        return Err("generated anyOS _start stub is outside the file".to_string());
    }

    let stub = &data[entry_off..entry_off + 20];
    let expected_tail = [
        0x48, 0x89, 0xc7, // mov rdi, rax
        0x48, 0x89, 0xfb, // mov rbx, rdi
        0x48, 0xc7, 0xc0, 0x01, 0x00, 0x00, 0x00, // mov rax, SYS_EXIT
        0x0f, 0x05, // syscall
    ];
    if stub[0] != 0xe8 || stub[5..20] != expected_tail {
        return Err("generated anyOS _start stub does not match syscall ABI".to_string());
    }
    Ok(())
}

pub fn to_flat_binary(data: &[u8]) -> Result<Vec<u8>, String> {
    let hdr = parse_elf64_header(data)?;
    let headers = load_segments(data)?;
    let base = headers
        .iter()
        .map(|ph| ph.vaddr)
        .min()
        .ok_or_else(|| "ELF has no PT_LOAD segments".to_string())?;
    let mut flat = flatten_segments(data, &headers, base, AddressKind::Virtual)?;
    install_flat_entry_trampoline(&mut flat, hdr.entry, base)?;
    Ok(flat)
}

pub fn to_physical_flat_binary(data: &[u8], base_paddr: u64) -> Result<Vec<u8>, String> {
    let headers = load_segments(data)?;
    flatten_segments(data, &headers, base_paddr, AddressKind::Physical)
}

pub fn to_dlib_v3(data: &[u8]) -> Result<Vec<u8>, String> {
    let headers = load_segments(data)?;
    let ro_segments = headers
        .iter()
        .copied()
        .filter(|ph| ph.flags & PF_W == 0)
        .collect::<Vec<_>>();
    let rw_segments = headers
        .iter()
        .copied()
        .filter(|ph| ph.flags & PF_W != 0)
        .collect::<Vec<_>>();

    if ro_segments.is_empty() {
        return Err("DLIB has no read-only PT_LOAD segment".to_string());
    }

    let base = ro_segments.iter().map(|ph| ph.vaddr).min().unwrap();
    let (ro_size, data_size, bss_size) = if rw_segments.is_empty() {
        let ro_end = ro_segments
            .iter()
            .map(|ph| ph.vaddr.saturating_add(ph.memsz))
            .max()
            .unwrap_or(base);
        (align_up(ro_end.saturating_sub(base), PAGE_SIZE), 0, 0)
    } else {
        let rw_start = rw_segments.iter().map(|ph| ph.vaddr).min().unwrap();
        let rw_file_end = rw_segments
            .iter()
            .map(|ph| ph.vaddr.saturating_add(ph.filesz))
            .max()
            .unwrap_or(rw_start);
        let rw_mem_end = rw_segments
            .iter()
            .map(|ph| ph.vaddr.saturating_add(ph.memsz))
            .max()
            .unwrap_or(rw_start);
        let ro_size = align_up(rw_start.saturating_sub(base), PAGE_SIZE);
        let data_size = align_up(rw_file_end.saturating_sub(rw_start), PAGE_SIZE);
        let total_rw = align_up(rw_mem_end.saturating_sub(rw_start), PAGE_SIZE);
        (ro_size, data_size, total_rw.saturating_sub(data_size))
    };

    let content_size = ro_size
        .checked_add(data_size)
        .ok_or_else(|| "DLIB content size overflow".to_string())?;
    let mut content = vec![0u8; content_size as usize];
    copy_segments_to_virtual_base(data, &headers, base, &mut content)?;

    let ro_pages = (ro_size / PAGE_SIZE) as u32;
    let data_pages = (data_size / PAGE_SIZE) as u32;
    let bss_pages = (bss_size / PAGE_SIZE) as u32;
    let total_pages = ro_pages + data_pages + bss_pages;

    let mut out = vec![0u8; PAGE_SIZE as usize];
    out[0..4].copy_from_slice(b"DLIB");
    write_u32(&mut out, 0x04, 3);
    write_u32(&mut out, 0x08, PAGE_SIZE as u32);
    write_u32(&mut out, 0x0c, 0);
    write_u64(&mut out, 0x10, base);
    write_u32(&mut out, 0x18, ro_pages);
    write_u32(&mut out, 0x1c, data_pages);
    write_u32(&mut out, 0x20, bss_pages);
    write_u32(&mut out, 0x24, total_pages);
    out.extend_from_slice(&content);
    Ok(out)
}

pub fn to_kdrv(data: &[u8], exports_offset: u64) -> Result<Vec<u8>, String> {
    let mut headers = load_segments(data)?;
    headers.sort_by_key(|ph| ph.vaddr);
    let base_vaddr = headers[0].vaddr & !(PAGE_SIZE - 1);

    let mut code_size = 0u64;
    let mut data_file_size = 0u64;
    let mut bss_size_raw = 0u64;
    for ph in &headers {
        let seg_off = ph
            .vaddr
            .checked_sub(base_vaddr)
            .ok_or_else(|| "KDRV segment before base address".to_string())?;
        if ph.flags & PF_W != 0 {
            let data_base = align_up(code_size, PAGE_SIZE);
            let data_off = seg_off
                .checked_sub(data_base)
                .ok_or_else(|| "KDRV writable segment overlaps code area".to_string())?;
            data_file_size = data_file_size.max(data_off.saturating_add(ph.filesz));
            bss_size_raw = bss_size_raw.max(ph.memsz.saturating_sub(ph.filesz));
        } else {
            code_size = code_size.max(seg_off.saturating_add(ph.filesz));
        }
    }

    let code_pages = pages_for(code_size);
    let data_pages = pages_for(data_file_size);
    let bss_pages = pages_for(bss_size_raw);
    let mut code = vec![0u8; (code_pages as u64 * PAGE_SIZE) as usize];
    let mut data_out = vec![0u8; (data_pages as u64 * PAGE_SIZE) as usize];

    for ph in &headers {
        let seg_off = ph.vaddr - base_vaddr;
        let src = segment_file_range(data, ph)?;
        if ph.flags & PF_W != 0 {
            let data_base = align_up(code_size, PAGE_SIZE);
            let dest = seg_off
                .checked_sub(data_base)
                .ok_or_else(|| "KDRV writable segment overlaps code area".to_string())?
                as usize;
            data_out[dest..dest + src.len()].copy_from_slice(src);
        } else {
            let dest = seg_off as usize;
            code[dest..dest + src.len()].copy_from_slice(src);
        }
    }

    let mut out = vec![0u8; PAGE_SIZE as usize];
    out[0..4].copy_from_slice(b"KDRV");
    write_u32(&mut out, 4, 1);
    write_u32(&mut out, 8, 1);
    write_u32(&mut out, 12, 0);
    write_u64(&mut out, 16, exports_offset);
    write_u32(&mut out, 24, code_pages);
    write_u32(&mut out, 28, data_pages);
    write_u32(&mut out, 32, bss_pages);
    out.extend_from_slice(&code);
    out.extend_from_slice(&data_out);
    Ok(out)
}

pub fn parse_elf64_header(data: &[u8]) -> Result<Elf64Header, String> {
    if data.len() < 64 {
        return Err("ELF64 file too small".to_string());
    }
    if &data[0..4] != ELF_MAGIC {
        return Err("not an ELF file".to_string());
    }
    if data[4] != ELFCLASS64 {
        return Err("not an ELF64 file".to_string());
    }
    if data[5] != ELFDATA2LSB {
        return Err("ELF64 file is not little-endian".to_string());
    }
    if u16_at(data, 16) != ET_EXEC {
        return Err("ELF64 file is not ET_EXEC".to_string());
    }
    if u16_at(data, 18) != EM_X86_64 {
        return Err("ELF64 file is not EM_X86_64".to_string());
    }
    if u16_at(data, 52) != 64 {
        return Err("ELF64 header size is not 64 bytes".to_string());
    }

    Ok(Elf64Header {
        entry: u64_at(data, 24),
        phoff: u64_at(data, 32) as usize,
        phentsize: u16_at(data, 54) as usize,
        phnum: u16_at(data, 56) as usize,
    })
}

pub fn program_headers(data: &[u8], hdr: &Elf64Header) -> Result<Vec<ProgramHeader>, String> {
    if hdr.phentsize != 56 {
        return Err("ELF64 program header size is not 56 bytes".to_string());
    }
    if hdr.phnum == 0 {
        return Err("ELF64 executable has no program headers".to_string());
    }
    let table_size = hdr
        .phentsize
        .checked_mul(hdr.phnum)
        .ok_or_else(|| "ELF64 program header table size overflow".to_string())?;
    let table_end = hdr
        .phoff
        .checked_add(table_size)
        .ok_or_else(|| "ELF64 program header table offset overflow".to_string())?;
    if table_end > data.len() {
        return Err("ELF64 program header table is outside the file".to_string());
    }

    let mut headers = Vec::new();
    for idx in 0..hdr.phnum {
        let off = hdr.phoff + idx * hdr.phentsize;
        headers.push(ProgramHeader {
            ty: u32_at(data, off),
            flags: u32_at(data, off + 4),
            offset: u64_at(data, off + 8),
            vaddr: u64_at(data, off + 16),
            paddr: u64_at(data, off + 24),
            filesz: u64_at(data, off + 32),
            memsz: u64_at(data, off + 40),
            align: u64_at(data, off + 48),
        });
    }
    Ok(headers)
}

#[derive(Debug, Clone, Copy)]
enum AddressKind {
    Virtual,
    Physical,
}

fn load_segments(data: &[u8]) -> Result<Vec<ProgramHeader>, String> {
    let hdr = parse_elf64_header(data)?;
    let headers = program_headers(data, &hdr)?
        .into_iter()
        .filter(|ph| ph.ty == PT_LOAD)
        .collect::<Vec<_>>();
    if headers.is_empty() {
        return Err("ELF has no PT_LOAD segments".to_string());
    }
    for ph in &headers {
        let _ = segment_file_range(data, ph)?;
    }
    Ok(headers)
}

fn flatten_segments(
    data: &[u8],
    headers: &[ProgramHeader],
    base: u64,
    kind: AddressKind,
) -> Result<Vec<u8>, String> {
    let end = headers
        .iter()
        .map(|ph| segment_addr(ph, kind).saturating_add(ph.memsz))
        .max()
        .ok_or_else(|| "ELF has no PT_LOAD segments".to_string())?;
    if end < base {
        return Err("flat binary base is above all segments".to_string());
    }
    let flat_size = end
        .checked_sub(base)
        .ok_or_else(|| "flat binary size underflow".to_string())?;
    let mut flat = vec![0u8; flat_size as usize];
    for ph in headers {
        let addr = segment_addr(ph, kind);
        let dest = addr
            .checked_sub(base)
            .ok_or_else(|| "PT_LOAD segment is below flat binary base".to_string())?
            as usize;
        let src = segment_file_range(data, ph)?;
        flat[dest..dest + src.len()].copy_from_slice(src);
    }
    Ok(flat)
}

fn copy_segments_to_virtual_base(
    data: &[u8],
    headers: &[ProgramHeader],
    base: u64,
    out: &mut [u8],
) -> Result<(), String> {
    for ph in headers {
        let dest = ph
            .vaddr
            .checked_sub(base)
            .ok_or_else(|| "PT_LOAD segment is below virtual base".to_string())?
            as usize;
        let src = segment_file_range(data, ph)?;
        let end = dest.saturating_add(src.len()).min(out.len());
        if end > dest {
            out[dest..end].copy_from_slice(&src[..end - dest]);
        }
    }
    Ok(())
}

fn segment_addr(ph: &ProgramHeader, kind: AddressKind) -> u64 {
    match kind {
        AddressKind::Virtual => ph.vaddr,
        AddressKind::Physical => ph.paddr,
    }
}

fn install_flat_entry_trampoline(flat: &mut [u8], entry: u64, base: u64) -> Result<(), String> {
    let entry_offset = entry
        .checked_sub(base)
        .ok_or_else(|| "flat binary entry point is below load base".to_string())?;
    if entry_offset == 0 {
        return Ok(());
    }
    if flat.len() < 5 {
        return Err("flat binary is too small for entry trampoline".to_string());
    }
    let rel = entry_offset as i64 - 5;
    if rel < i32::MIN as i64 || rel > i32::MAX as i64 {
        return Err("flat binary entry trampoline target is out of range".to_string());
    }
    flat[0] = 0xe9;
    flat[1..5].copy_from_slice(&(rel as i32).to_le_bytes());
    Ok(())
}

fn segment_file_range<'a>(data: &'a [u8], ph: &ProgramHeader) -> Result<&'a [u8], String> {
    let start = ph.offset as usize;
    let len = ph.filesz as usize;
    let end = start
        .checked_add(len)
        .ok_or_else(|| "ELF segment file range overflow".to_string())?;
    if end > data.len() {
        return Err("ELF segment reads past end of file".to_string());
    }
    Ok(&data[start..end])
}

fn contains_addr(ph: &ProgramHeader, addr: u64) -> bool {
    addr >= ph.vaddr && addr < ph.vaddr.saturating_add(ph.memsz)
}

fn u16_at(data: &[u8], off: usize) -> u16 {
    u16::from_le_bytes(data[off..off + 2].try_into().unwrap())
}

fn u32_at(data: &[u8], off: usize) -> u32 {
    u32::from_le_bytes(data[off..off + 4].try_into().unwrap())
}

fn u64_at(data: &[u8], off: usize) -> u64 {
    u64::from_le_bytes(data[off..off + 8].try_into().unwrap())
}

fn write_u32(data: &mut [u8], off: usize, value: u32) {
    data[off..off + 4].copy_from_slice(&value.to_le_bytes());
}

fn write_u64(data: &mut [u8], off: usize, value: u64) {
    data[off..off + 8].copy_from_slice(&value.to_le_bytes());
}

fn align_up(value: u64, align: u64) -> u64 {
    (value + align - 1) & !(align - 1)
}

fn pages_for(size: u64) -> u32 {
    if size == 0 {
        0
    } else {
        (align_up(size, PAGE_SIZE) / PAGE_SIZE) as u32
    }
}
