#!/usr/bin/env python3
"""
gen-uca.py — generate UCA primary-weight tables from the Unicode
DUCET (allkeys.txt).

Reads ``allkeys.txt`` (default: ``data/uca/allkeys.txt``) and produces:

  1. ``data/uca/uca.bin`` — binary file containing primary weights for all
     BMP single-codepoint entries. Format:

         offset  size  field
         0       4     magic = b"UCA1"
         4       2     version = 1 (LE u16)
         6       2     reserved
         8       4     entry_count (LE u32)
         12      4     reserved
         16+     8     entry: cp(u32 LE), primary1(u16 LE), primary2(u16 LE)

     Entries are sorted by codepoint. ``primary1 == 0`` means the
     codepoint is a collation-ignorable (combining marks, controls).
     ``primary2 != 0`` is used for two-element expansions (e.g. ``ß`` →
     ``ss``); a third element is dropped (rare for BMP).

  2. ``libs/libjs/src/vm/uca_latin_table.rs`` — Rust source containing a
     compile-time constant ``LATIN_PRIMARY_WEIGHTS: [[u16; 2]; 0x180]``
     covering U+0000..U+017F (Basic Latin + Latin-1 Supplement + Latin
     Extended-A). This is the embedded fallback table used when
     ``/System/share/collation/uca.bin`` is not present at runtime.
"""

import os
import re
import struct
import sys

REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(REPO, "data", "uca", "allkeys.txt")
OUT_BIN = os.path.join(REPO, "data", "uca", "uca.bin")
OUT_RS = os.path.join(REPO, "libs", "libjs", "src", "vm", "uca_latin_table.rs")

WEIGHT_RE = re.compile(r"\[[*.]?([0-9A-Fa-f]+)\.([0-9A-Fa-f]+)\.([0-9A-Fa-f]+)\]")


def parse_allkeys(path):
    """Yield (codepoint, [primary_weights]) for single-codepoint BMP entries."""
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line or line.startswith("@"):
                continue
            if ";" not in line:
                continue
            cps_str, weights_str = line.split(";", 1)
            cps = cps_str.strip().split()
            if len(cps) != 1:
                continue  # skip contractions
            cp = int(cps[0], 16)
            if cp > 0xFFFF:
                continue
            primaries = [int(m.group(1), 16) for m in WEIGHT_RE.finditer(weights_str)]
            yield cp, primaries


def main():
    if not os.path.exists(SRC):
        sys.stderr.write(
            f"error: {SRC} not found.\n"
            f"  Download it from https://www.unicode.org/Public/UCA/latest/allkeys.txt\n"
        )
        sys.exit(1)

    entries = []  # (cp, p1, p2)
    latin = [(0, 0)] * 0x180

    for cp, primaries in parse_allkeys(SRC):
        # Drop ignorable elements (primary == 0) before picking
        # the first/second non-ignorable weights, otherwise expansions
        # like ß = [s, ignorable, s] would lose their second s.
        primaries = [p for p in primaries if p != 0]
        p1 = primaries[0] if len(primaries) >= 1 else 0
        p2 = primaries[1] if len(primaries) >= 2 else 0
        # Clamp to u16 range — UCA primaries fit in u16 in practice
        if p1 > 0xFFFF or p2 > 0xFFFF:
            continue
        entries.append((cp, p1, p2))
        if cp < 0x180:
            latin[cp] = (p1, p2)

    entries.sort(key=lambda e: e[0])

    # ── Write uca.bin ──
    os.makedirs(os.path.dirname(OUT_BIN), exist_ok=True)
    with open(OUT_BIN, "wb") as f:
        f.write(b"UCA1")
        f.write(struct.pack("<HHII", 1, 0, len(entries), 0))
        for cp, p1, p2 in entries:
            f.write(struct.pack("<IHH", cp, p1, p2))
    print(f"wrote {OUT_BIN} ({os.path.getsize(OUT_BIN)} bytes, {len(entries)} entries)")

    # ── Write uca_latin_table.rs ──
    os.makedirs(os.path.dirname(OUT_RS), exist_ok=True)
    with open(OUT_RS, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by tools/gen-uca/gen-uca.py — DO NOT EDIT.\n")
        f.write("//\n")
        f.write("// Embedded UCA primary weights for U+0000..U+017F\n")
        f.write("// (Basic Latin + Latin-1 Supplement + Latin Extended-A).\n")
        f.write("// Used as fallback when /System/share/collation/uca.bin is\n")
        f.write("// not available at runtime.\n")
        f.write("//\n")
        f.write("// Each entry is [primary1, primary2]. primary1 == 0 means the\n")
        f.write("// codepoint is collation-ignorable; primary2 != 0 is used for\n")
        f.write("// two-element expansions like U+00DF (ß) → ss.\n\n")
        f.write("pub const LATIN_PRIMARY_WEIGHTS: [[u16; 2]; 0x180] = [\n")
        for cp, (p1, p2) in enumerate(latin):
            comment = ""
            if 0x20 <= cp < 0x7F:
                comment = f"  // U+{cp:04X} '{chr(cp)}'"
            elif cp < 0x180:
                comment = f"  // U+{cp:04X}"
            f.write(f"    [0x{p1:04X}, 0x{p2:04X}],{comment}\n")
        f.write("];\n")
    print(f"wrote {OUT_RS} ({sum(1 for p1,p2 in latin if p1)} non-zero entries)")


if __name__ == "__main__":
    main()
