[package]
name = "libwxecore"
version = "0.1.0"
edition = "2021"

[dependencies]
anyos_std = { path = "../stdlib" }
libconf_schema = { path = "../libconf_schema" }
libhttp_client = { path = "../libhttp_client" }
libtls = { path = "../libtls" }

[features]
default = []
host = ["anyos_std/host", "libconf_schema/host", "libhttp_client/host", "libtls/host"]

[lib]
name = "libwxecore"
