use alloc::format;
use alloc::string::String;
use alloc::vec::Vec;

use crate::logic::designer;
use crate::util::path;

const SCENE_W: u32 = 230;
const SCENE_H: u32 = 170;

#[derive(Clone, Debug)]
pub struct StoryboardScene {
    pub form_name: String,
    pub designer_path: String,
    pub x: i32,
    pub y: i32,
}

#[derive(Clone, Debug)]
pub struct StoryboardSegue {
    pub id: String,
    pub from_form: String,
    pub from_control: String,
    pub trigger_event: String,
    pub to_form: String,
    pub condition: String,
    pub navigation_mode: String,
    pub handler: String,
}

#[derive(Clone, Debug)]
pub struct StoryboardDocument {
    pub name: String,
    pub scenes: Vec<StoryboardScene>,
    pub segues: Vec<StoryboardSegue>,
}

impl StoryboardDocument {
    pub fn parse(file_path: &str, data: &str) -> Self {
        let mut doc = Self {
            name: storyboard_name(file_path),
            scenes: Vec::new(),
            segues: Vec::new(),
        };
        for line in data.split('\n') {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') || trimmed == "anycode-storyboard-v1"
            {
                continue;
            }
            if trimmed.starts_with("scene ") {
                doc.scenes.push(StoryboardScene {
                    form_name: attr(trimmed, "form").unwrap_or_else(|| String::from("Form")),
                    designer_path: attr(trimmed, "designer").unwrap_or_default(),
                    x: attr_i32(trimmed, "x", 40),
                    y: attr_i32(trimmed, "y", 40),
                });
            } else if trimmed.starts_with("segue ") {
                doc.segues.push(StoryboardSegue {
                    id: attr(trimmed, "id").unwrap_or_default(),
                    from_form: attr(trimmed, "from_form").unwrap_or_default(),
                    from_control: attr(trimmed, "from_control").unwrap_or_default(),
                    trigger_event: attr(trimmed, "trigger_event")
                        .unwrap_or_else(|| String::from("OnClick")),
                    to_form: attr(trimmed, "to_form").unwrap_or_default(),
                    condition: attr(trimmed, "condition").unwrap_or_default(),
                    navigation_mode: attr(trimmed, "navigation_mode")
                        .unwrap_or_else(|| String::from("SameWindow")),
                    handler: attr(trimmed, "handler").unwrap_or_default(),
                });
            }
        }
        doc
    }

    pub fn to_metadata(&self) -> String {
        let mut out = String::from("anycode-storyboard-v1\n");
        for scene in &self.scenes {
            out.push_str(&format!(
                "scene form=\"{}\" designer=\"{}\" x={} y={}\n",
                escape(&scene.form_name),
                escape(&scene.designer_path),
                scene.x,
                scene.y
            ));
        }
        for segue in &self.segues {
            out.push_str(&format!(
                "segue id=\"{}\" from_form=\"{}\" from_control=\"{}\" trigger_event=\"{}\" to_form=\"{}\" condition=\"{}\" navigation_mode=\"{}\" handler=\"{}\"\n",
                escape(&segue.id),
                escape(&segue.from_form),
                escape(&segue.from_control),
                escape(&segue.trigger_event),
                escape(&segue.to_form),
                escape(&segue.condition),
                escape(&segue.navigation_mode),
                escape(&segue.handler)
            ));
        }
        out
    }

    pub fn designer_rs(&self) -> String {
        let mut out =
            String::from("// Generated by anyCode Storyboard Designer. Do not edit by hand.\n\n");
        out.push_str("pub struct StoryboardSceneDef {\n");
        out.push_str("    pub form_name: &'static str,\n");
        out.push_str("    pub designer_path: &'static str,\n");
        out.push_str("    pub x: i32,\n");
        out.push_str("    pub y: i32,\n");
        out.push_str("}\n\n");
        out.push_str("pub struct StoryboardSegueDef {\n");
        out.push_str("    pub id: &'static str,\n");
        out.push_str("    pub from_form: &'static str,\n");
        out.push_str("    pub from_control: &'static str,\n");
        out.push_str("    pub trigger_event: &'static str,\n");
        out.push_str("    pub to_form: &'static str,\n");
        out.push_str("    pub condition: &'static str,\n");
        out.push_str("    pub navigation_mode: &'static str,\n");
        out.push_str("    pub handler: &'static str,\n");
        out.push_str("}\n\n");
        out.push_str(&format!(
            "pub const STORYBOARD_NAME: &str = \"{}\";\n\n",
            escape_rs(&self.name)
        ));
        out.push_str("pub const SCENES: &[StoryboardSceneDef] = &[\n");
        for scene in &self.scenes {
            out.push_str(&format!(
                "    StoryboardSceneDef {{ form_name: \"{}\", designer_path: \"{}\", x: {}, y: {} }},\n",
                escape_rs(&scene.form_name),
                escape_rs(&scene.designer_path),
                scene.x,
                scene.y
            ));
        }
        out.push_str("];\n\n");
        out.push_str("pub const SEGUES: &[StoryboardSegueDef] = &[\n");
        for segue in &self.segues {
            out.push_str(&format!(
                "    StoryboardSegueDef {{ id: \"{}\", from_form: \"{}\", from_control: \"{}\", trigger_event: \"{}\", to_form: \"{}\", condition: \"{}\", navigation_mode: \"{}\", handler: \"{}\" }},\n",
                escape_rs(&segue.id),
                escape_rs(&segue.from_form),
                escape_rs(&segue.from_control),
                escape_rs(&segue.trigger_event),
                escape_rs(&segue.to_form),
                escape_rs(&segue.condition),
                escape_rs(&segue.navigation_mode),
                escape_rs(&segue.handler)
            ));
        }
        out.push_str("];\n");
        out
    }

    pub fn codebehind_rs(&self) -> String {
        let mut out =
            String::from("// Generated by anyCode Storyboard Designer. Keep custom logic in the marked hooks.\n\n");
        out.push_str("pub fn storyboard_target(segue_id: &str) -> Option<&'static str> {\n");
        out.push_str("    match segue_id {\n");
        for segue in &self.segues {
            out.push_str(&format!(
                "        \"{}\" => Some(\"{}\"),\n",
                escape_rs(&segue.id),
                escape_rs(&segue.to_form)
            ));
        }
        out.push_str("        _ => None,\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");
        out.push_str("pub fn storyboard_can_navigate(segue_id: &str) -> bool {\n");
        out.push_str("    match segue_id {\n");
        for segue in &self.segues {
            if segue.condition.is_empty() {
                out.push_str(&format!("        \"{}\" => true,\n", escape_rs(&segue.id)));
            } else {
                out.push_str(&format!(
                    "        \"{}\" => {},\n",
                    escape_rs(&segue.id),
                    condition_function_name(&segue.condition)
                ));
            }
        }
        out.push_str("        _ => false,\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");
        out.push_str("pub fn storyboard_navigate(form_name: &str) {\n");
        out.push_str("    let _ = form_name;\n");
        out.push_str("    // TODO: connect this to the application navigation host.\n");
        out.push_str("}\n");
        out
    }

    pub fn scene_at(&self, x: i32, y: i32) -> Option<usize> {
        self.scenes.iter().position(|scene| {
            x >= scene.x
                && y >= scene.y
                && x < scene.x + SCENE_W as i32
                && y < scene.y + SCENE_H as i32
        })
    }

    pub fn control_anchor_at(&self, x: i32, y: i32) -> Option<(String, String)> {
        for scene in &self.scenes {
            let Some(form) = designer::load_designer(&scene.designer_path) else {
                continue;
            };
            for control in &form.controls {
                let (ax, ay) = control_anchor(scene, control);
                let dx = x - ax;
                let dy = y - ay;
                if dx * dx + dy * dy <= 64 {
                    return Some((scene.form_name.clone(), control.name.clone()));
                }
            }
        }
        None
    }

    pub fn add_segue(
        &mut self,
        from_form: &str,
        from_control: &str,
        trigger_event: &str,
        to_form: &str,
    ) -> Option<StoryboardSegue> {
        if from_form == to_form {
            return None;
        }
        if self.segues.iter().any(|segue| {
            segue.from_form == from_form
                && segue.from_control == from_control
                && same_event(&segue.trigger_event, trigger_event)
                && segue.to_form == to_form
        }) {
            return None;
        }
        let id = format!(
            "{}_{}_to_{}",
            to_module_name(from_form),
            to_module_name(from_control),
            to_module_name(to_form)
        );
        let handler = format!(
            "{}_navigate_to_{}",
            to_module_name(from_control),
            to_module_name(to_form)
        );
        let segue = StoryboardSegue {
            id,
            from_form: String::from(from_form),
            from_control: String::from(from_control),
            trigger_event: String::from(trigger_event),
            to_form: String::from(to_form),
            condition: String::new(),
            navigation_mode: String::from("SameWindow"),
            handler,
        };
        self.segues.push(segue.clone());
        Some(segue)
    }

    pub fn segue_by_id(&self, segue_id: &str) -> Option<&StoryboardSegue> {
        self.segues.iter().find(|segue| segue.id == segue_id)
    }

    pub fn remove_segue(&mut self, segue_id: &str) -> Option<StoryboardSegue> {
        let index = self.segues.iter().position(|segue| segue.id == segue_id)?;
        Some(self.segues.remove(index))
    }

    pub fn update_segue_property(
        &mut self,
        segue_id: &str,
        property_name: &str,
        value: &str,
    ) -> Result<(), &'static str> {
        let Some(segue) = self.segues.iter_mut().find(|segue| segue.id == segue_id) else {
            return Err("Storyboard segue not found");
        };
        match property_name {
            "TriggerEvent" => segue.trigger_event = String::from(value.trim()),
            "ToForm" => segue.to_form = String::from(value.trim()),
            "Condition" => segue.condition = String::from(value.trim()),
            "NavigationMode" => segue.navigation_mode = normalized_navigation_mode(value),
            "Handler" => segue.handler = String::from(value.trim()),
            _ => return Err("Storyboard segue property is read-only"),
        }
        Ok(())
    }

    pub fn add_missing_scenes(&mut self, project_root: &str) -> usize {
        let discovered = discover_scenes(project_root);
        let mut added = 0usize;
        for scene in discovered {
            let already_present = self.scenes.iter().any(|existing| {
                existing.designer_path == scene.designer_path
                    || existing.form_name == scene.form_name
            });
            if already_present {
                continue;
            }
            let idx = self.scenes.len();
            self.scenes.push(StoryboardScene {
                form_name: scene.form_name,
                designer_path: scene.designer_path,
                x: 36 + ((idx as i32 % 3) * 280),
                y: 42 + ((idx as i32 / 3) * 220),
            });
            added += 1;
        }
        added
    }
}

pub fn is_storyboard_file(file_path: &str) -> bool {
    file_path.ends_with(".Storyboard")
}

pub fn load_storyboard(file_path: &str) -> Option<StoryboardDocument> {
    let data = anyos_std::fs::read_to_string(file_path).ok()?;
    let mut doc = StoryboardDocument::parse(file_path, &data);
    if doc.scenes.is_empty() {
        if let Some(root) = project_root_for(file_path) {
            doc.scenes = discover_scenes(&root);
        }
    }
    Some(doc)
}

pub fn discover_storyboards(project_root: &str) -> Vec<String> {
    let mut out = Vec::new();
    discover_storyboard_files(&format!("{}/src", project_root), &mut out, 0);
    out
}

pub fn save_storyboard(file_path: &str, doc: &StoryboardDocument) -> Result<(), &'static str> {
    let mut normalized = doc.clone();
    if normalized.scenes.is_empty() {
        if let Some(root) = project_root_for(file_path) {
            normalized.scenes = discover_scenes(&root);
        }
    }
    anyos_std::fs::write_bytes(file_path, normalized.to_metadata().as_bytes())
        .map_err(|_| "Could not write storyboard")?;
    regenerate_generated_files(file_path, &normalized)
}

pub fn sync_document_with_project(
    storyboard_path: &str,
    doc: &mut StoryboardDocument,
) -> Result<usize, &'static str> {
    let Some(root) = project_root_for(storyboard_path) else {
        return Err("Could not find project root for storyboard");
    };
    let added = doc.add_missing_scenes(&root);
    if added > 0 {
        save_storyboard(storyboard_path, doc)?;
    }
    Ok(added)
}

pub fn sync_storyboards_for_project(project_root: &str) -> usize {
    let mut changed = 0usize;
    for storyboard_path in discover_storyboards(project_root) {
        let Some(mut doc) = load_storyboard(&storyboard_path) else {
            continue;
        };
        let added = doc.add_missing_scenes(project_root);
        if added == 0 {
            continue;
        }
        if save_storyboard(&storyboard_path, &doc).is_ok() {
            changed += 1;
        }
    }
    changed
}

pub fn designer_rs_path(storyboard_path: &str) -> String {
    format!("{}.Designer.rs", storyboard_path)
}

pub fn codebehind_rs_path(storyboard_path: &str) -> String {
    format!("{}.codebehind.rs", storyboard_path)
}

pub fn regenerate_generated_files(
    storyboard_path: &str,
    doc: &StoryboardDocument,
) -> Result<(), &'static str> {
    anyos_std::fs::write_bytes(
        &designer_rs_path(storyboard_path),
        doc.designer_rs().as_bytes(),
    )
    .map_err(|_| "Could not write storyboard designer code")?;
    anyos_std::fs::write_bytes(
        &codebehind_rs_path(storyboard_path),
        doc.codebehind_rs().as_bytes(),
    )
    .map_err(|_| "Could not write storyboard codebehind")?;
    Ok(())
}

pub fn apply_segue(
    storyboard_path: &str,
    doc: &mut StoryboardDocument,
    from_form: &str,
    from_control: &str,
    trigger_event: &str,
    to_form: &str,
) -> Result<Option<StoryboardSegue>, &'static str> {
    let Some(segue) = doc.add_segue(from_form, from_control, trigger_event, to_form) else {
        return Ok(None);
    };
    save_storyboard(storyboard_path, doc)?;
    write_navigation_handler(doc, &segue)?;
    Ok(Some(segue))
}

pub fn ensure_startup_main(
    project_root: &str,
    storyboard_path: &str,
) -> Result<bool, &'static str> {
    let main_path = format!("{}/src/main.rs", project_root);
    if path::exists(&main_path) {
        return Ok(false);
    }
    let doc = load_storyboard(storyboard_path).ok_or("Could not load startup storyboard")?;
    let scene = doc
        .scenes
        .first()
        .ok_or("Startup storyboard has no forms")?;
    let form =
        designer::load_designer(&scene.designer_path).ok_or("Could not load startup form")?;
    let module_name = module_name_for_designer_path(&scene.designer_path, &form.form_name);
    let code = startup_main_rs(
        storyboard_path,
        &module_name,
        &form.form_name,
        &form.title,
        form.width,
        form.height,
    );
    let _ = anyos_std::fs::mkdir(&format!("{}/src", project_root));
    anyos_std::fs::write_bytes(&main_path, code.as_bytes())
        .map_err(|_| "Could not write src/main.rs")?;
    Ok(true)
}

pub fn scene_size() -> (u32, u32) {
    (SCENE_W, SCENE_H)
}

pub fn control_anchor(scene: &StoryboardScene, control: &designer::DesignerControl) -> (i32, i32) {
    let local_x = control.x / 3 + (control.width / 6) as i32;
    let local_y = control.y / 3 + (control.height / 6) as i32;
    (scene.x + 16 + local_x, scene.y + 36 + local_y)
}

fn write_navigation_handler(
    doc: &StoryboardDocument,
    segue: &StoryboardSegue,
) -> Result<(), &'static str> {
    let Some(scene) = doc
        .scenes
        .iter()
        .find(|scene| scene.form_name == segue.from_form)
    else {
        return Err("Source form not found");
    };
    let mut form =
        designer::load_designer(&scene.designer_path).ok_or("Could not load source form")?;
    form.update_control_property(&segue.from_control, &segue.trigger_event, &segue.handler)?;
    designer::save_designer(&scene.designer_path, &form)?;

    let events_path = designer::events_file_for_designer(&scene.designer_path);
    let signature = format!("pub fn {}()", segue.handler);
    let mut data = anyos_std::fs::read_to_string(&events_path).unwrap_or_default();
    if !data.contains(&signature) {
        if !data.ends_with('\n') {
            data.push('\n');
        }
        data.push_str(&format!(
            "\npub fn {}() {{\n    if storyboard_can_navigate(\"{}\") {{\n        storyboard_navigate(\"{}\");\n    }}\n}}\n",
            segue.handler,
            escape(&segue.id),
            escape(&segue.to_form)
        ));
        if !data.contains("fn storyboard_can_navigate(") {
            data.push_str(
                "\nfn storyboard_can_navigate(_segue_id: &str) -> bool {\n    true\n}\n\nfn storyboard_navigate(_form_name: &str) {\n    // TODO: connect this to the app navigation host.\n}\n",
            );
        }
        anyos_std::fs::write_bytes(&events_path, data.as_bytes())
            .map_err(|_| "Could not update navigation event")?;
    }
    Ok(())
}

fn discover_scenes(project_root: &str) -> Vec<StoryboardScene> {
    let mut out = Vec::new();
    let ui_dir = format!("{}/src/ui", project_root);
    discover_designer_files(&ui_dir, &mut out, 0);
    for (idx, scene) in out.iter_mut().enumerate() {
        scene.x = 36 + ((idx as i32 % 3) * 280);
        scene.y = 42 + ((idx as i32 / 3) * 220);
    }
    out
}

pub fn trigger_event_options_for_control(kind: &str) -> &'static str {
    match kind {
        "Button" | "PlainButton" | "IconButton" | "ImageButton" | "LinkLabel" | "Tag" | "Label"
        | "Canvas" => "OnClick",
        "TextField" | "TextArea" | "TextEditor" | "SearchField" | "AutoCompleteTextField" => {
            "OnSubmit|OnChanged|OnClick"
        }
        "ListBox" | "TreeView" | "DataGrid" | "TableView" | "ComboBox" | "DropDown"
        | "RadioGroup" | "SegmentedControl" | "TabBar" => "OnChanged|OnSubmit|OnClick",
        "CheckBox" | "RadioButton" | "Toggle" | "Slider" | "Stepper" | "DatePicker"
        | "DateTimePicker" | "TimePicker" | "ColorWell" => "OnChanged|OnClick",
        _ => "OnClick|OnChanged|OnSubmit|OnDoubleClick",
    }
}

fn same_event(left: &str, right: &str) -> bool {
    left.eq_ignore_ascii_case(right)
}

fn discover_designer_files(dir: &str, out: &mut Vec<StoryboardScene>, depth: u32) {
    if depth > 4 {
        return;
    }
    let Ok(entries) = anyos_std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries {
        let full = path::join(dir, &entry.name);
        if entry.is_dir() {
            discover_designer_files(&full, out, depth + 1);
        } else if designer::is_designer_file(&full) {
            if let Some(form) = designer::load_designer(&full) {
                out.push(StoryboardScene {
                    form_name: form.form_name,
                    designer_path: full,
                    x: 0,
                    y: 0,
                });
            }
        }
    }
}

fn discover_storyboard_files(dir: &str, out: &mut Vec<String>, depth: u32) {
    if depth > 6 {
        return;
    }
    let Ok(entries) = anyos_std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries {
        let full = path::join(dir, &entry.name);
        if entry.is_dir() {
            discover_storyboard_files(&full, out, depth + 1);
        } else if is_storyboard_file(&full) {
            out.push(full);
        }
    }
}

fn project_root_for(file_path: &str) -> Option<String> {
    let mut dir = String::from(path::parent(file_path));
    for _ in 0..6 {
        if path::exists(&format!("{}/src/ui", dir)) {
            return Some(dir);
        }
        let parent = path::parent(&dir);
        if parent == dir {
            break;
        }
        dir = String::from(parent);
    }
    None
}

fn storyboard_name(file_path: &str) -> String {
    let base = path::basename(file_path);
    base.strip_suffix(".Storyboard")
        .map(String::from)
        .unwrap_or_else(|| String::from(base))
}

fn attr(line: &str, key: &str) -> Option<String> {
    let pat = format!("{}=\"", key);
    let start = line.find(&pat)? + pat.len();
    let rest = &line[start..];
    let end = rest.find('"')?;
    Some(unescape(&rest[..end]))
}

fn attr_i32(line: &str, key: &str, default: i32) -> i32 {
    let pat = format!("{}=", key);
    let Some(start) = line.find(&pat).map(|idx| idx + pat.len()) else {
        return default;
    };
    let rest = &line[start..];
    let end = rest.find(' ').unwrap_or(rest.len());
    rest[..end].parse::<i32>().unwrap_or(default)
}

fn escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn escape_rs(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
}

fn startup_main_rs(
    storyboard_path: &str,
    module_name: &str,
    form_name: &str,
    title: &str,
    width: u32,
    height: u32,
) -> String {
    format!(
        "#![no_std]\n#![no_main]\n\nuse libanyui_client as ui;\nuse ui::Widget;\n\n#[path = \"ui/{}/mod.rs\"]\nmod {};\n\nconst STARTUP_STORYBOARD: &str = \"{}\";\n\nanyos_std::entry!(main);\n\nfn main() {{\n    if !ui::init() {{\n        anyos_std::println!(\"Failed to load libanyui.so\");\n        return;\n    }}\n\n    let form = {}::{}::new();\n    form.root().set_dock(ui::DOCK_FILL);\n\n    let win = ui::Window::new(\"{}\", -1, -1, {}, {});\n    win.add(form.root());\n\n    let _ = STARTUP_STORYBOARD;\n    ui::run();\n}}\n",
        escape_rs(module_name),
        module_name,
        escape_rs(storyboard_path),
        module_name,
        form_name,
        escape_rs(title),
        width,
        height
    )
}

fn module_name_for_designer_path(designer_path: &str, form_name: &str) -> String {
    let parent = path::parent(designer_path);
    let module = path::basename(parent);
    if module.is_empty() {
        to_module_name(form_name)
    } else {
        String::from(module)
    }
}

fn unescape(value: &str) -> String {
    let mut out = String::new();
    let mut escaped = false;
    for ch in value.chars() {
        if escaped {
            out.push(ch);
            escaped = false;
        } else if ch == '\\' {
            escaped = true;
        } else {
            out.push(ch);
        }
    }
    out
}

fn to_module_name(name: &str) -> String {
    let mut out = String::new();
    for (idx, ch) in name.chars().enumerate() {
        if ch.is_ascii_alphanumeric() {
            if ch.is_ascii_uppercase() && idx > 0 && !out.ends_with('_') {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else if !out.ends_with('_') {
            out.push('_');
        }
    }
    out.trim_matches('_').into()
}

fn condition_function_name(condition: &str) -> String {
    let normalized = to_module_name(condition);
    if normalized.is_empty() {
        String::from("true")
    } else {
        format!("{}()", normalized)
    }
}

fn normalized_navigation_mode(value: &str) -> String {
    match value.trim().to_ascii_lowercase().as_str() {
        "newwindow" | "new window" | "window" => String::from("NewWindow"),
        "dialog" | "modal" => String::from("Dialog"),
        _ => String::from("SameWindow"),
    }
}
