//! Syscall number-to-name mapping table.
//!
//! Provides a static lookup table used for debug logging and introspection of
//! syscall numbers.

use super::*;

/// Function signature for a generic three-argument syscall handler.
pub type SyscallFn = fn(u32, u32, u32) -> u32;

/// Static table mapping syscall numbers to their human-readable names.
pub const SYSCALL_TABLE: &[(u32, &str)] = &[
    (SYS_EXIT, "exit"),
    (SYS_WRITE, "write"),
    (SYS_READ, "read"),
    (SYS_OPEN, "open"),
    (SYS_CLOSE, "close"),
    (SYS_GETPID, "getpid"),
    (SYS_YIELD, "yield"),
    (SYS_SLEEP, "sleep"),
    (SYS_SBRK, "sbrk"),
    (SYS_FORK, "fork"),
    (SYS_EXEC, "exec"),
    (SYS_WAITPID, "waitpid"),
    (SYS_TRY_WAITPID, "try_waitpid"),
    (SYS_KILL, "kill"),
    (SYS_MMAP, "mmap"),
    (SYS_MUNMAP, "munmap"),
    (SYS_DEVLIST, "devlist"),
    (SYS_DEVOPEN, "devopen"),
    (SYS_DEVCLOSE, "devclose"),
    (SYS_DEVREAD, "devread"),
    (SYS_DEVWRITE, "devwrite"),
    (SYS_DEVIOCTL, "devioctl"),
    (SYS_IRQWAIT, "irqwait"),
    (SYS_READDIR, "readdir"),
    (SYS_STAT, "stat"),
    (SYS_GETCWD, "getcwd"),
    (SYS_CHDIR, "chdir"),
    (SYS_SPAWN, "spawn"),
    (SYS_DETACH, "detach"),
    (SYS_GETARGS, "getargs"),
    (SYS_TRY_WAITPID, "try_waitpid"),
    (SYS_TIME, "time"),
    (SYS_UPTIME, "uptime"),
    (SYS_SYSINFO, "sysinfo"),
    (SYS_DMESG, "dmesg"),
    (SYS_TICK_HZ, "tick_hz"),
    (SYS_UPTIME_MS, "uptime_ms"),
    (SYS_SLEEP_US, "sleep_us"),
    (SYS_NET_CONFIG, "net_config"),
    (SYS_NET_PING, "net_ping"),
    (SYS_NET_DHCP, "net_dhcp"),
    (SYS_NET_DNS, "net_dns"),
    (SYS_NET_ARP, "net_arp"),
    (SYS_PIPE_CREATE, "pipe_create"),
    (SYS_PIPE_READ, "pipe_read"),
    (SYS_PIPE_CLOSE, "pipe_close"),
    (SYS_PIPE_WRITE, "pipe_write"),
    (SYS_PIPE_OPEN, "pipe_open"),
    (SYS_PIPE_LIST, "pipe_list"),
    (SYS_SETENV, "setenv"),
    (SYS_GETENV, "getenv"),
    (SYS_LISTENV, "listenv"),
    (SYS_KBD_GET_LAYOUT, "kbd_get_layout"),
    (SYS_KBD_SET_LAYOUT, "kbd_set_layout"),
    (SYS_KBD_LIST_LAYOUTS, "kbd_list_layouts"),
    (SYS_SYMLINK, "symlink"),
    (SYS_READLINK, "readlink"),
    (SYS_LSTAT, "lstat"),
    (SYS_RENAME, "rename"),
    (SYS_FTRUNCATE, "ftruncate"),
    (SYS_GET_CAPABILITIES, "get_capabilities"),
    (SYS_BOOT_READY, "boot_ready"),
    (SYS_GPU_HAS_ACCEL, "gpu_has_accel"),
    (SYS_GPU_HAS_HW_CURSOR, "gpu_has_hw_cursor"),
    (SYS_SHM_CREATE, "shm_create"),
    (SYS_SHM_MAP, "shm_map"),
    (SYS_SHM_UNMAP, "shm_unmap"),
    (SYS_SHM_DESTROY, "shm_destroy"),
    (SYS_MAP_FRAMEBUFFER, "map_framebuffer"),
    (SYS_GPU_COMMAND, "gpu_command"),
    (SYS_INPUT_POLL, "input_poll"),
    (SYS_REGISTER_COMPOSITOR, "register_compositor"),
    (SYS_CURSOR_TAKEOVER, "cursor_takeover"),
    (SYS_GETUID, "getuid"),
    (SYS_GETGID, "getgid"),
    (SYS_AUTHENTICATE, "authenticate"),
    (SYS_CHMOD, "chmod"),
    (SYS_CHOWN, "chown"),
    (SYS_ADDUSER, "adduser"),
    (SYS_DELUSER, "deluser"),
    (SYS_LISTUSERS, "listusers"),
    (SYS_ADDGROUP, "addgroup"),
    (SYS_DELGROUP, "delgroup"),
    (SYS_LISTGROUPS, "listgroups"),
    (SYS_GETUSERNAME, "getusername"),
    (SYS_SET_IDENTITY, "set_identity"),
    (SYS_PIPE2, "pipe2"),
    (SYS_DUP, "dup"),
    (SYS_DUP2, "dup2"),
    (SYS_FCNTL, "fcntl"),
    (SYS_SIGACTION, "sigaction"),
    (SYS_SIGPROCMASK, "sigprocmask"),
    (SYS_SIGRETURN, "sigreturn"),
    (SYS_GETPPID, "getppid"),
    (SYS_PERM_CHECK, "perm_check"),
    (SYS_PERM_STORE, "perm_store"),
    (SYS_PERM_LIST, "perm_list"),
    (SYS_PERM_DELETE, "perm_delete"),
    (SYS_PERM_PENDING_INFO, "perm_pending_info"),
    (SYS_REGISTER_SESSIONHOST, "register_sessionhost"),
    (SYS_GPU_VRAM_SIZE, "gpu_vram_size"),
    (SYS_VRAM_MAP, "vram_map"),
    (SYS_GPU_REGISTER_BACKBUFFER, "gpu_register_backbuffer"),
    (SYS_GET_CRASH_INFO, "get_crash_info"),
    (SYS_TCP_CONNECT, "tcp_connect"),
    (SYS_TCP_SEND, "tcp_send"),
    (SYS_TCP_RECV, "tcp_recv"),
    (SYS_TCP_CLOSE, "tcp_close"),
    (SYS_TCP_STATUS, "tcp_status"),
    (SYS_TCP_RECV_AVAILABLE, "tcp_recv_available"),
    (SYS_TCP_SHUTDOWN_WR, "tcp_shutdown_wr"),
    (SYS_TCP_LISTEN, "tcp_listen"),
    (SYS_TCP_ACCEPT, "tcp_accept"),
    (SYS_TCP_ACCEPT_NOWAIT, "tcp_accept_nowait"),
    (SYS_TCP_LIST, "tcp_list"),
    (SYS_UDP_LIST, "udp_list"),
    (SYS_NET_STATS, "net_stats"),
    (SYS_PIPE_BYTES_AVAILABLE, "pipe_bytes_available"),
    (SYS_WIFI, "wifi"),
    (SYS_GPU_3D_SUBMIT, "gpu_3d_submit"),
    (SYS_GPU_3D_QUERY, "gpu_3d_query"),
    (SYS_GPU_3D_SYNC, "gpu_3d_sync"),
    (SYS_GPU_3D_SURFACE_DMA, "gpu_3d_surface_dma"),
    (SYS_GPU_3D_SURFACE_DMA_READ, "gpu_3d_surface_dma_read"),
    (SYS_GPU_QUERY_TYPE, "gpu_query_type"),
    (SYS_GPU_3D_RESOURCE_CREATE, "gpu_3d_resource_create"),
    (SYS_GPU_3D_RESOURCE_DESTROY, "gpu_3d_resource_destroy"),
    (SYS_GET_HOSTNAME, "get_hostname"),
    (SYS_SET_HOSTNAME, "set_hostname"),
    (SYS_SHUTDOWN, "shutdown"),
    (SYS_SYNC, "sync"),
    (SYS_FSYNC, "fsync"),
    (SYS_SET_SERIAL_VERBOSE, "set_serial_verbose"),
    (SYS_CON_WRITE, "con_write"),
    (SYS_CON_READ, "con_read"),
    (SYS_CON_POLL_KEY, "con_poll_key"),
    (SYS_CON_GET_SIZE, "con_get_size"),
    (SYS_CON_SET_MODE, "con_set_mode"),
    // Platform / thermal / ACPI / I²C
    (SYS_THERMAL_READ, "thermal_read"),
    (SYS_THERMAL_CPU, "thermal_cpu"),
    (SYS_ACPI_SLEEP, "acpi_sleep"),
    (SYS_ACPI_PERF, "acpi_perf"),
    (SYS_I2C_READ, "i2c_read"),
    (SYS_I2C_WRITE, "i2c_write"),
    (SYS_I2C_DETECT, "i2c_detect"),
    // Monitor detection
    (SYS_MONITOR_COUNT, "monitor_count"),
    (SYS_MONITOR_INFO, "monitor_info"),
    (SYS_MONITOR_EDID, "monitor_edid"),
    (SYS_MONITOR_MODES, "monitor_modes"),
    // Debug / trace (anyTrace)
    (SYS_DEBUG_ATTACH, "debug_attach"),
    (SYS_DEBUG_DETACH, "debug_detach"),
    (SYS_DEBUG_SUSPEND, "debug_suspend"),
    (SYS_DEBUG_RESUME, "debug_resume"),
    (SYS_DEBUG_GET_REGS, "debug_get_regs"),
    (SYS_DEBUG_SET_REGS, "debug_set_regs"),
    (SYS_DEBUG_READ_MEM, "debug_read_mem"),
    (SYS_DEBUG_WRITE_MEM, "debug_write_mem"),
    (SYS_DEBUG_SET_BREAKPOINT, "debug_set_breakpoint"),
    (SYS_DEBUG_CLR_BREAKPOINT, "debug_clr_breakpoint"),
    (SYS_DEBUG_SINGLE_STEP, "debug_single_step"),
    (SYS_DEBUG_GET_MEM_MAP, "debug_get_mem_map"),
    (SYS_DEBUG_WAIT_EVENT, "debug_wait_event"),
    (SYS_THREAD_INFO_EX, "thread_info_ex"),
    // Hardware virtualization (VT-x / AMD-V)
    (SYS_VM_CREATE, "vm_create"),
    (SYS_VM_DESTROY, "vm_destroy"),
    (SYS_VM_SET_MEMORY, "vm_set_memory"),
    (SYS_VM_SET_CPUID, "vm_set_cpuid"),
    (SYS_VM_HW_INFO, "vm_hw_info"),
    (SYS_VM_GET_DIRTY_LOG, "vm_get_dirty_log"),
    (SYS_VCPU_CREATE, "vcpu_create"),
    (SYS_VCPU_RUN, "vcpu_run"),
    (SYS_VCPU_PAUSE, "vcpu_pause"),
    (SYS_VCPU_RESUME, "vcpu_resume"),
    (SYS_VCPU_GET_REGS, "vcpu_get_regs"),
    (SYS_VCPU_SET_REGS, "vcpu_set_regs"),
    (SYS_VCPU_GET_SREGS, "vcpu_get_sregs"),
    (SYS_VCPU_SET_SREGS, "vcpu_set_sregs"),
    (SYS_VCPU_GET_FPU, "vcpu_get_fpu"),
    (SYS_VCPU_SET_FPU, "vcpu_set_fpu"),
    (SYS_VCPU_INJECT_IRQ, "vcpu_inject_irq"),
    (SYS_VCPU_INJECT_EXCEPTION, "vcpu_inject_exception"),
    (SYS_VCPU_INJECT_NMI, "vcpu_inject_nmi"),
    (SYS_VCPU_GET_MP_STATE, "vcpu_get_mp_state"),
    (SYS_VCPU_SET_MP_STATE, "vcpu_set_mp_state"),
    (SYS_VCPU_TRANSLATE, "vcpu_translate"),
    (SYS_AVM_IOCTL, "avm_ioctl"),
    (SYS_MMAP64, "mmap64"),
    (SYS_MUNMAP64, "munmap64"),
];

/// Look up the human-readable name for a syscall number.
pub fn syscall_name(num: u32) -> &'static str {
    for &(n, name) in SYSCALL_TABLE {
        if n == num {
            return name;
        }
    }
    "unknown"
}
