//! Syscall number-to-name mapping table.
//!
//! Provides a static lookup table used for debug logging and introspection of
//! syscall numbers.

use super::*;

/// Function signature for a generic three-argument syscall handler.
pub type SyscallFn = fn(u32, u32, u32) -> u32;

/// Static table mapping syscall numbers to their human-readable names.
pub const SYSCALL_TABLE: &[(u32, &str)] = &[
    (SYS_EXIT, "exit"),
    (SYS_WRITE, "write"),
    (SYS_READ, "read"),
    (SYS_OPEN, "open"),
    (SYS_CLOSE, "close"),
    (SYS_GETPID, "getpid"),
    (SYS_YIELD, "yield"),
    (SYS_SLEEP, "sleep"),
    (SYS_SBRK, "sbrk"),
    (SYS_FORK, "fork"),
    (SYS_EXEC, "exec"),
    (SYS_WAITPID, "waitpid"),
    (SYS_TRY_WAITPID, "try_waitpid"),
    (SYS_KILL, "kill"),
    (SYS_MMAP, "mmap"),
    (SYS_MUNMAP, "munmap"),
    (SYS_DEVLIST, "devlist"),
    (SYS_DEVOPEN, "devopen"),
    (SYS_DEVCLOSE, "devclose"),
    (SYS_DEVREAD, "devread"),
    (SYS_DEVWRITE, "devwrite"),
    (SYS_DEVIOCTL, "devioctl"),
    (SYS_IRQWAIT, "irqwait"),
    (SYS_READDIR, "readdir"),
    (SYS_STAT, "stat"),
    (SYS_GETCWD, "getcwd"),
    (SYS_CHDIR, "chdir"),
    (SYS_SPAWN, "spawn"),
    (SYS_GETARGS, "getargs"),
    (SYS_TRY_WAITPID, "try_waitpid"),
    (SYS_TIME, "time"),
    (SYS_UPTIME, "uptime"),
    (SYS_SYSINFO, "sysinfo"),
    (SYS_DMESG, "dmesg"),
    (SYS_TICK_HZ, "tick_hz"),
    (SYS_UPTIME_MS, "uptime_ms"),
    (SYS_PIPE_CREATE, "pipe_create"),
    (SYS_PIPE_READ, "pipe_read"),
    (SYS_PIPE_CLOSE, "pipe_close"),
    (SYS_PIPE_WRITE, "pipe_write"),
    (SYS_PIPE_OPEN, "pipe_open"),
    (SYS_PIPE_LIST, "pipe_list"),
    (SYS_KBD_GET_LAYOUT, "kbd_get_layout"),
    (SYS_KBD_SET_LAYOUT, "kbd_set_layout"),
    (SYS_KBD_LIST_LAYOUTS, "kbd_list_layouts"),
    (SYS_SYMLINK, "symlink"),
    (SYS_READLINK, "readlink"),
    (SYS_LSTAT, "lstat"),
    (SYS_RENAME, "rename"),
    (SYS_FTRUNCATE, "ftruncate"),
    (SYS_GET_CAPABILITIES, "get_capabilities"),
    (SYS_BOOT_READY, "boot_ready"),
    (SYS_GETUID, "getuid"),
    (SYS_GETGID, "getgid"),
    (SYS_AUTHENTICATE, "authenticate"),
    (SYS_CHMOD, "chmod"),
    (SYS_CHOWN, "chown"),
    (SYS_ADDUSER, "adduser"),
    (SYS_DELUSER, "deluser"),
    (SYS_LISTUSERS, "listusers"),
    (SYS_ADDGROUP, "addgroup"),
    (SYS_DELGROUP, "delgroup"),
    (SYS_LISTGROUPS, "listgroups"),
    (SYS_GETUSERNAME, "getusername"),
    (SYS_SET_IDENTITY, "set_identity"),
    (SYS_PIPE2, "pipe2"),
    (SYS_DUP, "dup"),
    (SYS_DUP2, "dup2"),
    (SYS_FCNTL, "fcntl"),
    (SYS_SIGACTION, "sigaction"),
    (SYS_SIGPROCMASK, "sigprocmask"),
    (SYS_SIGRETURN, "sigreturn"),
    (SYS_GETPPID, "getppid"),
    (SYS_PERM_CHECK, "perm_check"),
    (SYS_PERM_STORE, "perm_store"),
    (SYS_PERM_LIST, "perm_list"),
    (SYS_PERM_DELETE, "perm_delete"),
    (SYS_PERM_PENDING_INFO, "perm_pending_info"),
    (SYS_GPU_VRAM_SIZE, "gpu_vram_size"),
    (SYS_VRAM_MAP, "vram_map"),
    (SYS_GPU_REGISTER_BACKBUFFER, "gpu_register_backbuffer"),
    (SYS_GET_CRASH_INFO, "get_crash_info"),
    (SYS_TCP_CONNECT, "tcp_connect"),
    (SYS_TCP_SEND, "tcp_send"),
    (SYS_TCP_RECV, "tcp_recv"),
    (SYS_TCP_CLOSE, "tcp_close"),
    (SYS_TCP_STATUS, "tcp_status"),
    (SYS_TCP_RECV_AVAILABLE, "tcp_recv_available"),
    (SYS_TCP_SHUTDOWN_WR, "tcp_shutdown_wr"),
    (SYS_TCP_LISTEN, "tcp_listen"),
    (SYS_TCP_ACCEPT, "tcp_accept"),
    (SYS_TCP_LIST, "tcp_list"),
    (SYS_UDP_LIST, "udp_list"),
    (SYS_NET_STATS, "net_stats"),
    (SYS_PIPE_BYTES_AVAILABLE, "pipe_bytes_available"),
    (SYS_GPU_3D_SUBMIT, "gpu_3d_submit"),
    (SYS_GPU_3D_QUERY, "gpu_3d_query"),
    (SYS_GPU_3D_SYNC, "gpu_3d_sync"),
    (SYS_GPU_3D_SURFACE_DMA, "gpu_3d_surface_dma"),
];

/// Look up the human-readable name for a syscall number.
pub fn syscall_name(num: u32) -> &'static str {
    for &(n, name) in SYSCALL_TABLE {
        if n == num {
            return name;
        }
    }
    "unknown"
}
